import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawn as nodeSpawn, type ChildProcess } from 'node:child_process';
import type { EventEmitter } from 'node:events';
import {
  mkdtempSync,
  rmSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WorkerManager, type SpawnFn } from '../../src/workers/manager.js';
import {
  MaestroProcess,
  MaestroTurnInFlightError,
  type MaestroEvent,
} from '../../src/orchestrator/maestro/process.js';
import { MAESTRO_SESSION_UUID } from '../../src/orchestrator/maestro/session.js';
import type { MaestroPromptVars } from '../../src/orchestrator/maestro/prompt-composer.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fakeInteractive = join(__dirname, '..', '..', 'tests', 'helpers', 'fake-claude-interactive.mjs');
const FAKE_INTERACTIVE = existsSync(fakeInteractive)
  ? fakeInteractive
  : join(__dirname, '..', 'helpers', 'fake-claude-interactive.mjs');

function spawner(scenario: string): SpawnFn {
  return (_command: string, _args: readonly string[], options): ChildProcess =>
    nodeSpawn(process.execPath, [FAKE_INTERACTIVE, scenario], options);
}

const VARS: MaestroPromptVars = {
  projectName: 'test-project',
  registeredProjects: 'test-project',
  workersInFlight: '(none)',
  currentMode: 'PLAN',
  autonomyDefault: '2',
  planModeRequired: false,
  previewCommand: '',
  availableTools: '',
  maestroWarmth: '',
};

const FIXTURE_PROMPT_BODY = `# fixture
## BEGIN PROMPT
You are Maestro. Active project: {project_name}. Mode: {current_mode}.
## END PROMPT
`;

let sandbox: string;
let home: string;
let promptsDir: string;
let cliEntry: string;

beforeEach(() => {
  sandbox = mkdtempSync(join(tmpdir(), 'symphony-maestro-process-'));
  home = join(sandbox, 'home');
  mkdirSync(home, { recursive: true });
  promptsDir = join(sandbox, 'prompts');
  mkdirSync(promptsDir, { recursive: true });
  writeFileSync(join(promptsDir, 'maestro-system-prompt-v1.md'), FIXTURE_PROMPT_BODY, 'utf8');
  cliEntry = join(sandbox, 'fake-cli.js');
  writeFileSync(cliEntry, '// placeholder cli for mcp-config tests\n', 'utf8');
});

afterEach(() => {
  try {
    rmSync(sandbox, { recursive: true, force: true });
  } catch {
    // ignore
  }
});

describe('MaestroProcess.start', () => {
  it('writes CLAUDE.md and mcp-config, spawns claude -p, resolves on system_init', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
      nodeBinary: '/abs/node',
    });
    try {
      const result = await maestro.start({ promptVars: VARS });
      expect(result.systemInit.sessionId).toBe('00000000-0000-4000-8000-000000000060');
      expect(result.workspace.cwd).toBe(join(home, '.symphony', 'maestro'));

      const claudeMd = readFileSync(result.workspace.claudeMdPath, 'utf8');
      expect(claudeMd).toContain('AUTOGENERATED by Symphony');
      expect(claudeMd).toContain('Active project: test-project');
      expect(claudeMd).toContain('Mode: PLAN');

      const mcpConfig = JSON.parse(readFileSync(result.mcpConfigPath, 'utf8'));
      expect(mcpConfig.mcpServers.symphony.command).toBe('/abs/node');
      expect(mcpConfig.mcpServers.symphony.args[0]).toBe(cliEntry);
      expect(mcpConfig.mcpServers.symphony.args[1]).toBe('mcp-server');
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });

  it('start() is idempotent-rejecting (twice throws)', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      await maestro.start({ promptVars: VARS });
      await expect(maestro.start({ promptVars: VARS })).rejects.toThrow(/start\(\) called twice/);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });

  it('cleans up CLAUDE.md + mcp-config when system_init never arrives (audit 2C.1 m4)', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-no-init'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    const workspaceCwd = join(home, '.symphony', 'maestro');
    const claudeMdPath = join(workspaceCwd, 'CLAUDE.md');
    let mcpConfigPath: string | undefined;
    // Snapshot the to-be-written mcp-config path post-failure: writeMaestroMcpConfig
    // emits a fixed filename in the workspace.
    try {
      await expect(maestro.start({ promptVars: VARS })).rejects.toThrow();
      // Both autogenerated files removed best-effort.
      expect(existsSync(claudeMdPath)).toBe(false);
      // mcp-config sits next to CLAUDE.md — read its expected path from the
      // workspace dir; if it survives, the test still asserts file absence.
      mcpConfigPath = mcpConfigPath ?? join(workspaceCwd, '.symphony-mcp.json');
      expect(existsSync(mcpConfigPath)).toBe(false);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });

  it('STOPPED_EVENT only fires once even if pumpEvents finally re-runs (audit 2C.1 m8)', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    let stopFireCount = 0;
    try {
      await maestro.start({ promptVars: VARS });
      // Reach into the emitter via the same Symbol the iterator uses.
      const STOPPED = Symbol.for('symphony.maestro.stopped');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const emitter = (maestro as any).emitter as EventEmitter;
      emitter.on(STOPPED, () => {
        stopFireCount += 1;
      });
      await maestro.kill();
      // Manually invoke the private emitter a second time to simulate the
      // "future kill-path emit" hypothetical the audit guards against.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (maestro as any).emitStopped();
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (maestro as any).emitStopped();
      expect(stopFireCount).toBe(1);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });
});

describe('MaestroProcess events', () => {
  it('emits assistant_text → tool_use → tool_result → turn_completed for one turn', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      await maestro.start({ promptVars: VARS });
      // Subscribe to events BEFORE sending the user message — `events()` is
      // a live stream (no replay), so the iterator must be live when
      // `sendUserMessage` synchronously emits `turn_started`.
      const collector = (async (): Promise<MaestroEvent[]> => {
        const out: MaestroEvent[] = [];
        for await (const event of maestro.events()) {
          out.push(event);
          if (event.type === 'turn_completed') break;
        }
        return out;
      })();
      // Yield to the microtask queue so `events()` registers its handler
      // before we synchronously emit turn_started.
      await Promise.resolve();
      maestro.sendUserMessage('first turn please');
      const events = await collector;
      const types = events.map((e) => e.type);
      expect(types).toContain('turn_started');
      expect(types).toContain('assistant_text');
      expect(types).toContain('tool_use');
      expect(types).toContain('tool_result');
      expect(types[types.length - 1]).toBe('turn_completed');
      const toolUse = events.find((e) => e.type === 'tool_use');
      expect(toolUse?.type).toBe('tool_use');
      if (toolUse?.type === 'tool_use') {
        expect(toolUse.name).toBe('spawn_worker');
        expect(toolUse.input).toEqual({ role: 'researcher', task: 'demo' });
      }
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });

  it('sendUserMessage before start() throws', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      expect(() => maestro.sendUserMessage('too early')).toThrow(/before start\(\)/);
    } finally {
      await mgr.shutdown();
    }
  });

  it('sendUserMessage during a streaming turn throws MaestroTurnInFlightError (audit M3)', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      await maestro.start({ promptVars: VARS });
      maestro.sendUserMessage('first turn please');
      // Turn is in flight — second call must reject loudly, not silently
      // queue the message into Maestro's already-running turn.
      expect(() => maestro.sendUserMessage('second please')).toThrow(MaestroTurnInFlightError);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });

  it('events() iterator attached after start() still sees backlog events (audit M2)', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      await maestro.start({ promptVars: VARS });
      // Send the user message FIRST, THEN start iterating — the
      // pre-subscribe backlog must replay turn_started for late iterators.
      maestro.sendUserMessage('first turn please');
      const out: MaestroEvent[] = [];
      for await (const event of maestro.events()) {
        out.push(event);
        if (event.type === 'turn_completed') break;
      }
      expect(out.map((e) => e.type)).toContain('turn_started');
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });
});

describe('MaestroProcess session continuity (audit C1)', () => {
  it('first-boot fresh session uses MAESTRO_SESSION_UUID, not the Worker.id-derived UUID', async () => {
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      spawn: spawner('maestro-process'),
      onStaleResume: () => {
        // expected on cold cwd
      },
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      const result = await maestro.start({ promptVars: VARS });
      // The fake-claude scenario emits its own hardcoded session_id on
      // system_init (not derived from --session-id). The contract under
      // test is that MaestroProcess passed the SENTINEL UUID to spawn,
      // NOT a different one derived from `cfg.id`.
      expect(MAESTRO_SESSION_UUID).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
      );
      expect(result.session.sessionId).toBe(MAESTRO_SESSION_UUID);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });
});

describe('MaestroProcess Stop hook env carve-out', () => {
  it('passes SYMPHONY_HOOK_PORT/TOKEN through extraEnv via allowExtraEnvKeys', async () => {
    const blocked: Array<{ id: string; key: string }> = [];
    const mgr = new WorkerManager({
      claudeConfigPath: join(home, '.claude.json'),
      claudeHome: home,
      onBlockedEnv: (id, key) => blocked.push({ id, key }),
      spawn: spawner('maestro-process'),
    });
    const maestro = new MaestroProcess({
      workerManager: mgr,
      home,
      promptsDir,
      cliEntryPath: cliEntry,
    });
    try {
      await maestro.start({
        promptVars: VARS,
        extraEnv: { SYMPHONY_HOOK_PORT: '54321', SYMPHONY_HOOK_TOKEN: 'tok' },
      });
      expect(blocked).toEqual([]);
    } finally {
      await maestro.kill().catch(() => undefined);
      await mgr.shutdown();
    }
  });
});
