import os from 'node:os';
import path from 'node:path';
import { promises as fsp } from 'node:fs';
import { randomBytes } from 'node:crypto';

const MAESTRO_WORKSPACE_DIR = '.symphony';
const MAESTRO_SUBDIR = 'maestro';
const CLAUDE_MD_FILENAME = 'CLAUDE.md';

export interface EnsureMaestroWorkspaceOptions {
  /** Override `os.homedir()` for tests. */
  home?: string;
}

export interface MaestroWorkspace {
  cwd: string;
  claudeMdPath: string;
}

/**
 * Create `<home>/.symphony/maestro/` if it doesn't exist. Idempotent. The
 * returned `cwd` is the absolute directory Claude (Maestro) is spawned in;
 * Claude Code reads `CLAUDE.md` from this directory natively.
 *
 * NOT a git repo — Maestro never commits. The trust-injection done in
 * `ensureClaudeTrust` keys off the absolute cwd path, which is fine for a
 * non-repo directory (the trust file is in `~/.claude.json`).
 */
export async function ensureMaestroWorkspace(
  options: EnsureMaestroWorkspaceOptions = {},
): Promise<MaestroWorkspace> {
  const home = options.home ?? os.homedir();
  const cwd = path.resolve(path.join(home, MAESTRO_WORKSPACE_DIR, MAESTRO_SUBDIR));
  await fsp.mkdir(cwd, { recursive: true });
  return {
    cwd,
    claudeMdPath: path.join(cwd, CLAUDE_MD_FILENAME),
  };
}

/**
 * Atomically (write-then-rename) replace Maestro's CLAUDE.md content.
 * Used at every `symphony start` boot — Maestro's prompt is regenerated
 * with fresh template variables (project list, in-flight workers, etc.).
 *
 * Caveat: user edits to this file are lost on next boot. The header banner
 * documents this. Phase 4D fragments will offer override surfaces.
 */
export async function writeMaestroClaudeMd(claudeMdPath: string, content: string): Promise<void> {
  // Random suffix avoids races between concurrent `symphony start` invocations
  // (legitimate or accidental). Both finish their writes; the second `rename`
  // wins and clobbers the first — but neither sees a half-written file.
  const tmp = `${claudeMdPath}.tmp-${randomBytes(6).toString('hex')}`;
  try {
    await fsp.writeFile(tmp, content, 'utf8');
    await fsp.rename(tmp, claudeMdPath);
  } catch (err) {
    // Best-effort cleanup so a write-or-rename failure doesn't leak the tmp.
    fsp.unlink(tmp).catch(() => {});
    throw err;
  }
}

export const MAESTRO_CLAUDE_MD_HEADER =
  '<!-- AUTOGENERATED by Symphony — edits will be overwritten on next `symphony start` boot. -->\n\n';
