import { execFile } from 'node:child_process';
import { promises as fsp, statSync } from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

/**
 * Phase 4D.2 — worker prompt injection (Multica pattern).
 *
 * Instead of re-sending the role opener + common suffix on stdin every
 * turn (the 4A seam), write the worker's "operating manual" once into
 * `<worktree>/CLAUDE.md` and let Claude Code discover it natively
 * (cheaper context, respects Anthropic's priority order). The TASK
 * stays on stdin (`PromptComposer.composeWorkerTaskKickoff`).
 *
 * Safety invariants:
 *  - NEVER overwrite a git-TRACKED project `CLAUDE.md`. `.git/info/exclude`
 *    (DEFAULT_GIT_EXCLUDE_PATTERNS already lists `CLAUDE.md`) only ignores
 *    UNtracked files; clobbering a tracked one would pollute the user's
 *    diff and risk the worker committing Symphony's manual into their
 *    repo. If the project tracks its own CLAUDE.md, fall back to the
 *    proven 4A stdin delivery — Claude Code still reads the project's
 *    real CLAUDE.md natively, and the manual rides stdin.
 *  - Any non-worktree path / fs error / git failure also falls back to
 *    stdin. The fallback is byte-identical to `composeWorkerPrompt`
 *    (4A), so 4D.2 is never worse than the shipped behavior.
 *  - Reuse detection via the sentinel header (mirrors
 *    `MAESTRO_CLAUDE_MD_HEADER`): a worktree whose CLAUDE.md already
 *    starts with our sentinel is a reused one → the caller prepends the
 *    verbatim `[NEW TASK]` staleness guard to the kickoff.
 */

/**
 * Sentinel that opens every Symphony-written worker CLAUDE.md. Doubles
 * as the reuse-detection marker. HTML comment so it's inert to Claude.
 */
export const WORKER_CLAUDE_MD_SENTINEL =
  '<!-- AUTOGENERATED by Symphony (worker role manual) — do not edit; regenerated per spawn. -->\n\n';

export type WorkerClaudeMdResult =
  | { readonly mode: 'claude-md'; readonly reused: boolean }
  | { readonly mode: 'stdin-fallback'; readonly reason: string };

/**
 * Injector signature — lifecycle-injectable so tests can stub the OS
 * boundary (mirrors the project's optional-dep convention). The default
 * is {@link defaultInjectWorkerClaudeMd}.
 */
export type InjectWorkerClaudeMd = (
  worktreePath: string,
  manual: string,
) => Promise<WorkerClaudeMdResult>;

/**
 * Sync on purpose: the fallback path (`false`) must add ZERO libuv
 * macrotasks so it doesn't perturb the spawn-pipeline tick budget that
 * the cap/queue/shutdown unit tests assert against (they stub the
 * worktree to a non-existent path → this returns false synchronously,
 * the async fn resolves on a microtask, and the tests' setImmediate
 * drains still cover it). A single `statSync` at spawn time is
 * negligible and consistent with `WorktreeManager`'s own `existsSync`.
 */
function isDirectory(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

async function isGitTracked(
  worktreePath: string,
  relPath: string,
): Promise<boolean> {
  try {
    await execFileAsync(
      'git',
      ['ls-files', '--error-unmatch', '--', relPath],
      { cwd: worktreePath },
    );
    return true;
  } catch {
    return false;
  }
}

/**
 * Default injector. Writes `<worktree>/CLAUDE.md` = sentinel + manual
 * atomically (tmp+rename) UNLESS the project tracks its own CLAUDE.md or
 * the path isn't a usable worktree, in which case it returns
 * `stdin-fallback` and the caller delivers the manual the 4A way.
 */
export const defaultInjectWorkerClaudeMd: InjectWorkerClaudeMd = async (
  worktreePath,
  manual,
) => {
  try {
    if (!isDirectory(worktreePath)) {
      return { mode: 'stdin-fallback', reason: 'not-a-worktree-dir' };
    }
    if (await isGitTracked(worktreePath, 'CLAUDE.md')) {
      // Project tracks its own CLAUDE.md — Claude Code reads it
      // natively; never overwrite a tracked file.
      return { mode: 'stdin-fallback', reason: 'project-tracks-claude-md' };
    }
    const target = path.join(worktreePath, 'CLAUDE.md');
    let existing: string | undefined;
    try {
      existing = await fsp.readFile(target, 'utf8');
    } catch {
      existing = undefined;
    }
    const reused = existing?.startsWith(WORKER_CLAUDE_MD_SENTINEL) ?? false;
    await writeAtomic(target, `${WORKER_CLAUDE_MD_SENTINEL}${manual}`);
    return { mode: 'claude-md', reused };
  } catch (err) {
    console.warn(
      `[worker-claude-md] injection failed for ${worktreePath}; ` +
        `falling back to stdin delivery: ${
          err instanceof Error ? err.message : String(err)
        }`,
    );
    return { mode: 'stdin-fallback', reason: 'error' };
  }
};

/**
 * tmp+rename atomic write — mirrors `workspace.ts:writeMaestroClaudeMd`.
 * Random suffix tolerates concurrent writers; a SIGKILL mid-write can't
 * truncate the discovered CLAUDE.md (worker would read a half file).
 */
async function writeAtomic(filePath: string, content: string): Promise<void> {
  const tmp = `${filePath}.tmp-${randomBytes(6).toString('hex')}`;
  try {
    await fsp.writeFile(tmp, content, 'utf8');
    await fsp.rename(tmp, filePath);
  } catch (err) {
    fsp.unlink(tmp).catch(() => {});
    throw err;
  }
}
