import { mkdtempSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  InvalidTaskIdError,
  mirrorTaskNotes,
  resolveTaskNotesPath,
} from '../../src/state/task-notes-mirror.js';
import type { TaskNote } from '../../src/state/types.js';

let tmpDir: string;
let projectPath: string;

beforeEach(() => {
  tmpDir = mkdtempSync(path.join(os.tmpdir(), 'sym-5c-mirror-'));
  projectPath = path.join(tmpDir, 'proj');
  mkdirSync(projectPath, { recursive: true });
});

afterEach(() => {
  try {
    rmSync(tmpDir, { recursive: true, force: true });
  } catch {
    // best effort
  }
});

const SAMPLE_NOTES: TaskNote[] = [
  { at: '2026-05-21T10:00:00.000Z', text: 'first note' },
  { at: '2026-05-21T11:00:00.000Z', text: 'second note' },
];

describe('resolveTaskNotesPath', () => {
  it('produces <projectPath>/.symphony/tasks/<taskId>/notes.md', () => {
    const out = resolveTaskNotesPath('/tmp/proj', 'tk-abc12345');
    expect(out).toBe(
      path.resolve('/tmp/proj/.symphony/tasks/tk-abc12345/notes.md'),
    );
  });

  it('rejects task ids containing path separators', () => {
    expect(() => resolveTaskNotesPath('/tmp/proj', '../escape')).toThrow(
      InvalidTaskIdError,
    );
    expect(() => resolveTaskNotesPath('/tmp/proj', 'foo/bar')).toThrow(
      InvalidTaskIdError,
    );
    expect(() => resolveTaskNotesPath('/tmp/proj', 'foo\\bar')).toThrow(
      InvalidTaskIdError,
    );
  });

  it('rejects empty and dot-prefixed task ids', () => {
    expect(() => resolveTaskNotesPath('/tmp/proj', '')).toThrow(InvalidTaskIdError);
    expect(() => resolveTaskNotesPath('/tmp/proj', '.hidden')).toThrow(
      InvalidTaskIdError,
    );
  });

  it('rejects overly long task ids', () => {
    expect(() => resolveTaskNotesPath('/tmp/proj', 'a'.repeat(65))).toThrow(
      InvalidTaskIdError,
    );
  });

  it('accepts standard tk-<hex> shape', () => {
    expect(() => resolveTaskNotesPath('/tmp/proj', 'tk-12345678')).not.toThrow();
  });

  it('rejects Win32 device-reserved names (audit m1)', () => {
    for (const reserved of ['CON', 'PRN', 'AUX', 'NUL', 'COM1', 'COM9', 'LPT1', 'LPT9']) {
      expect(() => resolveTaskNotesPath('/tmp/proj', reserved)).toThrow(
        InvalidTaskIdError,
      );
      // Case-insensitive — Windows device names match regardless of case.
      expect(() => resolveTaskNotesPath('/tmp/proj', reserved.toLowerCase())).toThrow(
        InvalidTaskIdError,
      );
    }
  });

  it('does NOT reject benign names sharing a prefix with reserved (CON1, NULL)', () => {
    expect(() => resolveTaskNotesPath('/tmp/proj', 'CON1')).not.toThrow();
    expect(() => resolveTaskNotesPath('/tmp/proj', 'NULL')).not.toThrow();
  });
});

describe('mirrorTaskNotes', () => {
  it('writes the mirror with auto-banner + formatted notes', async () => {
    const res = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(res.written).toBe(true);
    expect(res.path).toBe(
      path.resolve(projectPath, '.symphony/tasks/tk-aa11bb22/notes.md'),
    );
    const body = readFileSync(res.path!, 'utf8');
    expect(body).toContain('AUTOGENERATED by Symphony');
    expect(body).toContain('## 2026-05-21 10:00:00 UTC');
    expect(body).toContain('first note');
    expect(body).toContain('second note');
  });

  it('is idempotent — re-running with same input replaces the file cleanly', async () => {
    const first = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    const second = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(first.written).toBe(true);
    expect(second.written).toBe(true);
    expect(second.path).toBe(first.path);
    expect(readFileSync(second.path!, 'utf8')).toBe(readFileSync(first.path!, 'utf8'));
  });

  it('rewrites with the new note list on subsequent calls', async () => {
    await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: [SAMPLE_NOTES[0]!],
    });
    const res = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    const body = readFileSync(res.path!, 'utf8');
    expect(body).toContain('first note');
    expect(body).toContain('second note');
  });

  it('skips silently when projectPath is null', async () => {
    const res = await mirrorTaskNotes({
      projectPath: null,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(res.written).toBe(false);
    expect(res.skipReason).toBe('no-project-path');
    expect(res.path).toBeNull();
  });

  it('skips when projectPath does not exist on disk', async () => {
    const missing = path.join(tmpDir, 'does-not-exist');
    const res = await mirrorTaskNotes({
      projectPath: missing,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(res.written).toBe(false);
    expect(res.skipReason).toBe('project-path-missing');
  });

  it('reports write-failed when target is unwritable', async () => {
    // Write a file where the directory needs to go to force a write
    // failure on mkdir. The OS reports ENOTDIR / EEXIST.
    const blockingParent = path.join(projectPath, '.symphony');
    mkdirSync(path.dirname(blockingParent), { recursive: true });
    // Create a file named ".symphony" (collides with the directory we
    // need to create).
    const fs = await import('node:fs/promises');
    await fs.writeFile(blockingParent, 'block');
    const res = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(res.written).toBe(false);
    expect(res.skipReason).toBe('write-failed');
    expect(res.error).toBeInstanceOf(Error);
  });

  it('throws InvalidTaskIdError on malformed task id (defense)', async () => {
    await expect(
      mirrorTaskNotes({
        projectPath,
        taskId: '../escape',
        notes: SAMPLE_NOTES,
      }),
    ).rejects.toThrow(InvalidTaskIdError);
  });

  it('creates the nested .symphony/tasks/<id>/ directory automatically', async () => {
    const res = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-deepnest',
      notes: SAMPLE_NOTES,
    });
    expect(res.written).toBe(true);
    expect(res.path).toMatch(/[\\/]\.symphony[\\/]tasks[\\/]tk-deepnest[\\/]notes\.md$/);
  });

  it('writes an empty-but-banner-bearing file when notes array is empty', async () => {
    const res = await mirrorTaskNotes({
      projectPath,
      taskId: 'tk-empty00',
      notes: [],
    });
    expect(res.written).toBe(true);
    const body = readFileSync(res.path!, 'utf8');
    expect(body).toContain('AUTOGENERATED');
    // Empty notes → banner only, no section headers.
    expect(body).not.toContain('##');
  });

  it('returns the target path even when the write fails', async () => {
    const missing = path.join(tmpDir, 'does-not-exist');
    const res = await mirrorTaskNotes({
      projectPath: missing,
      taskId: 'tk-aa11bb22',
      notes: SAMPLE_NOTES,
    });
    expect(res.path).toMatch(/[\\/]\.symphony[\\/]tasks[\\/]tk-aa11bb22[\\/]notes\.md$/);
  });
});
