/**
 * Phase 5C — end-to-end preserve test for the task notes mirror.
 *
 * The Phase 5C claim that workers can `Read .symphony/tasks/<id>/notes.md`
 * from their worktree depends on the full pipeline:
 *
 *   git ls-files --others --exclude-standard / --ignored →
 *     matchesPreservePattern → copyFileExclusive
 *
 * Coverage in `preserve.test.ts` only exercises the middle step. This
 * integration test stitches the full chain together with a real git
 * repo + real fs against the production `preserveFilesToWorktree`
 * helper (the same function `WorktreeManager.create` calls). Without
 * this, a regression in pathspec construction or candidate discovery
 * would silently break the feature without any unit-test signal.
 *
 * Audit M2 fix.
 */
import { execFile } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  preserveFilesToWorktree,
  resolvePreservePatterns,
} from '../../src/worktree/preserve.js';

const execFileAsync = promisify(execFile);

async function git(cwd: string, ...args: string[]): Promise<void> {
  await execFileAsync('git', args, { cwd });
}

async function initRepo(repoPath: string): Promise<void> {
  mkdirSync(repoPath, { recursive: true });
  await git(repoPath, 'init', '--initial-branch=main');
  await git(repoPath, 'config', 'user.email', 'test@example.com');
  await git(repoPath, 'config', 'user.name', 'Symphony Test');
  await git(repoPath, 'config', 'commit.gpgsign', 'false');
  writeFileSync(path.join(repoPath, 'README.md'), '# demo\n');
  await git(repoPath, 'add', '.');
  await git(repoPath, 'commit', '-m', 'init');
}

let sandbox: string;
let sourceRepo: string;
let destDir: string;

beforeEach(async () => {
  sandbox = mkdtempSync(path.join(tmpdir(), 'sym-5c-preserve-'));
  sourceRepo = path.join(sandbox, 'src');
  destDir = path.join(sandbox, 'dest');
  mkdirSync(destDir, { recursive: true });
  await initRepo(sourceRepo);
});

afterEach(() => {
  try {
    rmSync(sandbox, { recursive: true, force: true });
  } catch {
    // best effort
  }
});

describe('Phase 5C — preserve pipeline carries task notes into worktrees', () => {
  it('copies .symphony/tasks/<id>/notes.md when .symphony/ is gitignored', async () => {
    // User opts to gitignore .symphony/ (typical).
    writeFileSync(path.join(sourceRepo, '.gitignore'), '.symphony/\n');
    await git(sourceRepo, 'add', '.gitignore');
    await git(sourceRepo, 'commit', '-m', 'gitignore .symphony');

    // Write the mirror file like `mirrorTaskNotes` would.
    const noteRel = '.symphony/tasks/tk-aa11bb22/notes.md';
    mkdirSync(path.join(sourceRepo, path.dirname(noteRel)), { recursive: true });
    writeFileSync(
      path.join(sourceRepo, noteRel),
      '<!-- AUTOGENERATED -->\n\n## 2026-05-21 10:00:00 UTC\n\nstarted work\n',
    );

    const { patterns } = resolvePreservePatterns(sourceRepo);
    expect(patterns).toContain('.symphony/tasks/**/notes.md');

    const result = await preserveFilesToWorktree(sourceRepo, destDir, patterns);
    expect(result.copied).toContain(noteRel);
    expect(existsSync(path.join(destDir, noteRel))).toBe(true);
    const body = readFileSync(path.join(destDir, noteRel), 'utf8');
    expect(body).toContain('started work');
  });

  it('copies .symphony/tasks/<id>/notes.md when .symphony/ is untracked (no .gitignore)', async () => {
    // User has NOT gitignored .symphony/ — file is just untracked.
    const noteRel = '.symphony/tasks/tk-deadbeef/notes.md';
    mkdirSync(path.join(sourceRepo, path.dirname(noteRel)), { recursive: true });
    writeFileSync(
      path.join(sourceRepo, noteRel),
      '<!-- AUTOGENERATED -->\n\n## 2026-05-21 10:00:00 UTC\n\nuntracked note\n',
    );

    const { patterns } = resolvePreservePatterns(sourceRepo);
    expect(patterns).toContain('.symphony/tasks/**/notes.md');

    const result = await preserveFilesToWorktree(sourceRepo, destDir, patterns);
    expect(result.copied).toContain(noteRel);
    expect(existsSync(path.join(destDir, noteRel))).toBe(true);
  });

  it('does NOT copy unrelated files inside .symphony/tasks/<id>/ (only notes.md)', async () => {
    writeFileSync(path.join(sourceRepo, '.gitignore'), '.symphony/\n');
    await git(sourceRepo, 'add', '.gitignore');
    await git(sourceRepo, 'commit', '-m', 'gitignore .symphony');

    const taskDir = path.join(sourceRepo, '.symphony/tasks/tk-aa11bb22');
    mkdirSync(taskDir, { recursive: true });
    writeFileSync(path.join(taskDir, 'notes.md'), '## ts\n\nbody\n');
    writeFileSync(path.join(taskDir, 'scratch.txt'), 'should not be preserved');
    writeFileSync(path.join(taskDir, 'audit.log'), 'should not be preserved');

    const { patterns } = resolvePreservePatterns(sourceRepo);
    const result = await preserveFilesToWorktree(sourceRepo, destDir, patterns);
    expect(result.copied).toContain('.symphony/tasks/tk-aa11bb22/notes.md');
    expect(result.copied).not.toContain('.symphony/tasks/tk-aa11bb22/scratch.txt');
    expect(result.copied).not.toContain('.symphony/tasks/tk-aa11bb22/audit.log');
    expect(
      existsSync(path.join(destDir, '.symphony/tasks/tk-aa11bb22/scratch.txt')),
    ).toBe(false);
  });

  it('copies notes from multiple task directories in one preserve call', async () => {
    writeFileSync(path.join(sourceRepo, '.gitignore'), '.symphony/\n');
    await git(sourceRepo, 'add', '.gitignore');
    await git(sourceRepo, 'commit', '-m', 'gitignore .symphony');

    for (const id of ['tk-aaaaaaaa', 'tk-bbbbbbbb', 'tk-cccccccc']) {
      mkdirSync(path.join(sourceRepo, `.symphony/tasks/${id}`), { recursive: true });
      writeFileSync(
        path.join(sourceRepo, `.symphony/tasks/${id}/notes.md`),
        `## ts\n\nnote for ${id}\n`,
      );
    }

    const { patterns } = resolvePreservePatterns(sourceRepo);
    const result = await preserveFilesToWorktree(sourceRepo, destDir, patterns);
    expect(result.copied).toEqual(
      expect.arrayContaining([
        '.symphony/tasks/tk-aaaaaaaa/notes.md',
        '.symphony/tasks/tk-bbbbbbbb/notes.md',
        '.symphony/tasks/tk-cccccccc/notes.md',
      ]),
    );
  });
});
