/**
 * Phase 5C integration — `task_notes` MCP tool against real SQLite +
 * real fs. Verifies the full chain:
 *
 *   tool.append → SqliteTaskStore.update → onNotesAppended →
 *   mirrorTaskNotes → tmp+rename atomic disk write
 *
 * Then exercises `task_notes(action:"read")` + `(action:"list")` and
 * confirms the disk file content matches the markdown blob the tool
 * returns. Mirrors are best-effort; tests verify they DO land in the
 * happy path AND fall back to the SQL-only path when the project root
 * disappears mid-flight.
 */
import { mkdtempSync, mkdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { DEFAULT_DISPATCH_CONTEXT } from '../../src/orchestrator/capabilities.js';
import { makeTaskNotesTool } from '../../src/orchestrator/tools/task-notes.js';
import { SymphonyDatabase } from '../../src/state/db.js';
import { SqliteProjectStore } from '../../src/state/sqlite-project-store.js';
import { SqliteTaskStore } from '../../src/state/sqlite-task-store.js';
import { mirrorTaskNotes } from '../../src/state/task-notes-mirror.js';
import { createTaskNotesMirrorQueue } from '../../src/state/task-notes-mirror-queue.js';

interface TaskNotesArgs {
  action: 'append' | 'read' | 'list';
  task_id?: string;
  text?: string;
  since?: string;
  limit?: number;
  project?: string;
}
function notesArgs(input: TaskNotesArgs): {
  action: 'append' | 'read' | 'list';
  task_id: string | undefined;
  text: string | undefined;
  since: string | undefined;
  limit: number | undefined;
  project: string | undefined;
} {
  return {
    action: input.action,
    task_id: input.task_id,
    text: input.text,
    since: input.since,
    limit: input.limit,
    project: input.project,
  };
}
import type { TaskSnapshot } from '../../src/state/types.js';

let sandbox: string;
let dbPath: string;
let db: SymphonyDatabase | undefined;
let projectRoot: string;

beforeEach(() => {
  sandbox = mkdtempSync(path.join(tmpdir(), 'sym-5c-int-'));
  dbPath = path.join(sandbox, 'symphony.db');
  projectRoot = path.join(sandbox, 'proj');
  mkdirSync(projectRoot, { recursive: true });
});

afterEach(() => {
  db?.close();
  db = undefined;
  try {
    rmSync(sandbox, { recursive: true, force: true });
  } catch {
    // best effort
  }
});

const CTX = { ...DEFAULT_DISPATCH_CONTEXT, mode: 'act' as const };

function expectedMirrorPath(taskId: string): string {
  return path.resolve(projectRoot, '.symphony', 'tasks', taskId, 'notes.md');
}

describe('Phase 5C integration — task_notes end-to-end', () => {
  it('append fires the disk mirror at .symphony/tasks/<id>/notes.md', async () => {
    db = SymphonyDatabase.open({ filePath: dbPath });
    const projectStore = new SqliteProjectStore(db.db);
    const projRecord = projectStore.register({
      id: 'demo',
      name: 'demo',
      path: projectRoot,
      createdAt: new Date().toISOString(),
    });
    let lastMirrorPromise: Promise<unknown> = Promise.resolve();
    const taskStore = new SqliteTaskStore(db.db, {
      onNotesAppended: (snapshot: TaskSnapshot) => {
        lastMirrorPromise = mirrorTaskNotes({
          projectPath: projectStore.get(snapshot.projectId)?.path ?? null,
          taskId: snapshot.id,
          notes: snapshot.notes,
        }).catch(() => undefined);
      },
    });
    const task = taskStore.create({
      projectId: projRecord.id,
      description: 'do thing',
    });

    const tool = makeTaskNotesTool({ taskStore, projectStore });

    const appendRes = await tool.handler(
      notesArgs({ action: 'append', task_id: task.id, text: 'first beat' }),
      CTX,
    );
    expect(appendRes.isError).toBeFalsy();

    // Deterministic — await the mirror chain instead of fixed-sleep
    // polling. The callback assigns to `lastMirrorPromise` so we can
    // wait for the rename to land regardless of CI parallel load.
    await lastMirrorPromise;

    const mirrorPath = expectedMirrorPath(task.id);
    expect(statSync(mirrorPath).isFile()).toBe(true);
    const body = readFileSync(mirrorPath, 'utf8');
    expect(body).toContain('AUTOGENERATED by Symphony');
    expect(body).toContain('first beat');
  });

  it('multiple appends rewrite the mirror with the full notes history', async () => {
    db = SymphonyDatabase.open({ filePath: dbPath });
    const projectStore = new SqliteProjectStore(db.db);
    const projRecord = projectStore.register({
      id: 'demo',
      name: 'demo',
      path: projectRoot,
      createdAt: new Date().toISOString(),
    });

    // Tracked last-enqueued promise so the test can `await` the
    // mirror chain instead of fixed-sleep polling. Under parallel CI
    // load `setTimeout(20)` raced the rename intermittently — the
    // explicit await is deterministic.
    const mirrorQueue = createTaskNotesMirrorQueue();
    let lastMirrorPromise: Promise<unknown> = Promise.resolve();
    const taskStore = new SqliteTaskStore(db.db, {
      onNotesAppended: (snapshot: TaskSnapshot) => {
        lastMirrorPromise = mirrorQueue
          .enqueue({
            projectPath: projectStore.get(snapshot.projectId)?.path ?? null,
            taskId: snapshot.id,
            notes: snapshot.notes,
          })
          .catch(() => undefined);
      },
    });
    const task = taskStore.create({ projectId: projRecord.id, description: 'x' });
    const tool = makeTaskNotesTool({ taskStore, projectStore });

    for (const text of ['first beat', 'second beat', 'third beat']) {
      const res = await tool.handler(
        notesArgs({ action: 'append', task_id: task.id, text }),
        CTX,
      );
      expect(res.isError).toBeFalsy();
    }
    await lastMirrorPromise;

    const body = readFileSync(expectedMirrorPath(task.id), 'utf8');
    expect(body).toContain('first beat');
    expect(body).toContain('second beat');
    expect(body).toContain('third beat');
  });

  it('read returns the same markdown blob as the disk mirror (modulo banner)', async () => {
    db = SymphonyDatabase.open({ filePath: dbPath });
    const projectStore = new SqliteProjectStore(db.db);
    const projRecord = projectStore.register({
      id: 'demo',
      name: 'demo',
      path: projectRoot,
      createdAt: new Date().toISOString(),
    });

    const mirrorQueue = createTaskNotesMirrorQueue();
    let lastMirrorPromise: Promise<unknown> = Promise.resolve();
    const taskStore = new SqliteTaskStore(db.db, {
      onNotesAppended: (snapshot: TaskSnapshot) => {
        lastMirrorPromise = mirrorQueue
          .enqueue({
            projectPath: projectStore.get(snapshot.projectId)?.path ?? null,
            taskId: snapshot.id,
            notes: snapshot.notes,
          })
          .catch(() => undefined);
      },
    });
    const task = taskStore.create({ projectId: projRecord.id, description: 'x' });
    const tool = makeTaskNotesTool({ taskStore, projectStore });

    await tool.handler(
      notesArgs({ action: 'append', task_id: task.id, text: 'progress one' }),
      CTX,
    );
    await tool.handler(
      notesArgs({ action: 'append', task_id: task.id, text: 'progress two' }),
      CTX,
    );
    await lastMirrorPromise;

    const readRes = await tool.handler(
      notesArgs({ action: 'read', task_id: task.id }),
      CTX,
    );
    const toolBody = readRes.content.map((c) => c.text).join('\n');
    const mirrorBody = readFileSync(expectedMirrorPath(task.id), 'utf8');

    // Mirror has the auto-banner; tool output does not. The body
    // sections beneath must be identical.
    expect(mirrorBody).toContain('AUTOGENERATED');
    expect(toolBody).not.toContain('AUTOGENERATED');
    const mirrorBeneathBanner = mirrorBody.slice(mirrorBody.indexOf('\n## '));
    const toolBeneathFirstHeader = toolBody.slice(toolBody.indexOf('## '));
    // Normalize leading whitespace (one extra newline in mirror).
    expect(mirrorBeneathBanner.trim()).toBe(toolBeneathFirstHeader.trim());
  });

  it('list returns one summary per task with notes', async () => {
    db = SymphonyDatabase.open({ filePath: dbPath });
    const projectStore = new SqliteProjectStore(db.db);
    const projRecord = projectStore.register({
      id: 'demo',
      name: 'demo',
      path: projectRoot,
      createdAt: new Date().toISOString(),
    });

    const taskStore = new SqliteTaskStore(db.db);
    const a = taskStore.create({ projectId: projRecord.id, description: 'a' });
    const b = taskStore.create({ projectId: projRecord.id, description: 'b' });
    taskStore.create({ projectId: projRecord.id, description: 'no-notes' });
    taskStore.update(a.id, { notes: 'note on a' });
    taskStore.update(b.id, { notes: 'note on b' });
    taskStore.update(b.id, { notes: 'second on b' });

    const tool = makeTaskNotesTool({ taskStore, projectStore });
    const res = await tool.handler(notesArgs({ action: 'list' }), CTX);
    const sc = res.structuredContent as {
      total: number;
      summaries: Array<{ taskId: string; count: number }>;
    };
    expect(sc.total).toBe(2);
    const bySummary = new Map(sc.summaries.map((s) => [s.taskId, s.count]));
    expect(bySummary.get(a.id)).toBe(1);
    expect(bySummary.get(b.id)).toBe(2);
  });

  it('SQL append still succeeds when projectPath is unregistered (mirror silently skipped)', async () => {
    db = SymphonyDatabase.open({ filePath: dbPath });
    const projectStore = new SqliteProjectStore(db.db);
    // Register a project for FK validity but DELETE the path on disk
    // so the mirror probe returns project-path-missing.
    const projRecord = projectStore.register({
      id: 'ghost',
      name: 'ghost',
      path: projectRoot,
      createdAt: new Date().toISOString(),
    });
    rmSync(projectRoot, { recursive: true, force: true });

    const skipReasons: string[] = [];
    let lastMirrorPromise: Promise<unknown> = Promise.resolve();
    const taskStore = new SqliteTaskStore(db.db, {
      onNotesAppended: (snapshot: TaskSnapshot) => {
        lastMirrorPromise = mirrorTaskNotes({
          projectPath: projectStore.get(snapshot.projectId)?.path ?? null,
          taskId: snapshot.id,
          notes: snapshot.notes,
        }).then((r) => {
          if (r.skipReason !== undefined) skipReasons.push(r.skipReason);
        });
      },
    });
    const task = taskStore.create({ projectId: projRecord.id, description: 'x' });
    const tool = makeTaskNotesTool({ taskStore, projectStore });

    const appendRes = await tool.handler(
      notesArgs({ action: 'append', task_id: task.id, text: 'ghost note' }),
      CTX,
    );
    expect(appendRes.isError).toBeFalsy();
    await lastMirrorPromise;

    // SQL has the note...
    const snap = taskStore.snapshot(task.id)!;
    expect(snap.notes.map((n) => n.text)).toEqual(['ghost note']);
    // ...but the mirror was skipped.
    expect(skipReasons).toContain('project-path-missing');
  });
});
