/**
 * Phase 5C — Task notes disk mirror.
 *
 * Writes a per-task notes file at
 * `<projectPath>/.symphony/tasks/<taskId>/notes.md` so workers spawned
 * for that task can `Read` prior context from their worktree, and so
 * humans can inspect notes outside Symphony.
 *
 * SQL is source of truth. This mirror is regenerated on every append
 * (cheap — tasks usually carry <100 notes). Mirror failures are logged
 * + swallowed: SQL has already accepted the append, the disk view is
 * a convenience.
 *
 * Atomic write: tmp+rename with a random suffix, mirroring
 * `writeMaestroClaudeMd` (`src/orchestrator/maestro/workspace.ts:49`).
 * Concurrent calls for the same task race on the rename — both finish
 * cleanly; the second clobbers the first; neither leaves a half-written
 * file. Different-task calls do not interact.
 */
import { promises as fsp } from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';

import { formatNotesAsMarkdown } from './task-notes-format.js';
import type { TaskNote } from './types.js';

const TASKS_SUBDIR = '.symphony';
const TASKS_INNER = 'tasks';
const NOTES_FILENAME = 'notes.md';
const TASK_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;
/**
 * Win32 device-reserved names — refused at the file-system layer
 * regardless of extension. Belt-and-suspenders defense (audit m1):
 * Symphony's auto-generated ids are `tk-<8hex>` and can't collide
 * today, but a future legacy-id migration or hand-supplied test
 * fixture passing one of these would silently produce a
 * `write-failed` skip on Windows. Reject at the boundary instead.
 */
const WIN32_RESERVED_TASK_IDS: ReadonlySet<string> = new Set([
  'CON',
  'PRN',
  'AUX',
  'NUL',
  'COM1',
  'COM2',
  'COM3',
  'COM4',
  'COM5',
  'COM6',
  'COM7',
  'COM8',
  'COM9',
  'LPT1',
  'LPT2',
  'LPT3',
  'LPT4',
  'LPT5',
  'LPT6',
  'LPT7',
  'LPT8',
  'LPT9',
]);

const HEADER_BANNER =
  '<!-- AUTOGENERATED by Symphony — Maestro task notes. Source of truth is SQLite (~/.symphony/symphony.db). This file is rewritten on every note append. -->\n\n';

export class InvalidTaskIdError extends Error {
  readonly taskId: string;
  constructor(taskId: string) {
    super(`Invalid task id for mirror: ${JSON.stringify(taskId)}`);
    this.name = 'InvalidTaskIdError';
    this.taskId = taskId;
  }
}

export interface MirrorTaskNotesInput {
  /**
   * Absolute project path. `null` or `undefined` short-circuits — no
   * mirror is written. Callers that resolved a `task.projectId` that
   * has no path (legacy in-memory mode, or unregistered project) pass
   * null here.
   */
  readonly projectPath: string | null | undefined;
  /** Task id. Must match `^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$`. */
  readonly taskId: string;
  /** Ordered note list (typically the full SQL `notes` JSON array). */
  readonly notes: readonly TaskNote[];
}

export interface MirrorTaskNotesResult {
  /** Absolute path written, or `null` when the mirror was skipped. */
  readonly path: string | null;
  /** True when the file was written. */
  readonly written: boolean;
  /** Why the mirror was skipped (when `written === false`). */
  readonly skipReason?:
    | 'no-project-path'
    | 'project-path-missing'
    | 'write-failed';
  /** Surfaced error when `skipReason === 'write-failed'`. */
  readonly error?: Error;
}

/**
 * Resolve the absolute path the mirror writes to for a given project +
 * task id. Pure — does NOT touch the filesystem. Throws
 * `InvalidTaskIdError` on a malformed task id (defense against path
 * traversal — current task ids are `tk-<8hex>` but the boundary is
 * worth fortifying).
 */
export function resolveTaskNotesPath(projectPath: string, taskId: string): string {
  if (!TASK_ID_PATTERN.test(taskId)) {
    throw new InvalidTaskIdError(taskId);
  }
  // Reject Win32 device-reserved basenames (CON/PRN/AUX/NUL/COM1–9/LPT1–9)
  // — they fail at the file-system layer on Windows even though the
  // pattern check accepts them. Audit m1.
  if (WIN32_RESERVED_TASK_IDS.has(taskId.toUpperCase())) {
    throw new InvalidTaskIdError(taskId);
  }
  return path.resolve(
    path.join(projectPath, TASKS_SUBDIR, TASKS_INNER, taskId, NOTES_FILENAME),
  );
}

/**
 * Write the disk mirror. Idempotent (re-running with identical input
 * produces the same file). Errors are caught + reported via the result
 * — callers should NOT throw on a mirror failure (SQL is source of
 * truth).
 *
 * Side-effect-free aside from the file write. When `projectPath` is
 * null/undefined or the project root does not exist on disk, returns
 * `{written: false, skipReason}` without touching the filesystem.
 */
export async function mirrorTaskNotes(
  input: MirrorTaskNotesInput,
): Promise<MirrorTaskNotesResult> {
  if (input.projectPath === null || input.projectPath === undefined) {
    return { path: null, written: false, skipReason: 'no-project-path' };
  }

  // Validate task id BEFORE touching fs so a malformed id never resolves
  // to an unsafe path. Throws InvalidTaskIdError (caller's choice to
  // propagate — server.ts wraps in try/catch and treats as write-failed).
  const target = resolveTaskNotesPath(input.projectPath, input.taskId);

  try {
    // Probe project root exists. The mirror only makes sense alongside
    // a real project directory — silently skipping on a missing root
    // matches the "registered but path moved/removed" edge case.
    await fsp.access(input.projectPath);
  } catch {
    return { path: target, written: false, skipReason: 'project-path-missing' };
  }

  const body = HEADER_BANNER + formatNotesAsMarkdown(input.notes);
  const dir = path.dirname(target);
  const tmp = `${target}.tmp-${randomBytes(6).toString('hex')}`;

  try {
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(tmp, body, 'utf8');
    await fsp.rename(tmp, target);
    return { path: target, written: true };
  } catch (err) {
    fsp.unlink(tmp).catch(() => {});
    return {
      path: target,
      written: false,
      skipReason: 'write-failed',
      error: err instanceof Error ? err : new Error(String(err)),
    };
  }
}
